### ISSUE TITLE
Comparison with other stylus packages

### ISSUE THREAD

**Issue by dandv** [furrio/meteor-stylus-multi#12]
There are [many stylus packages on Atmosphere](https://atmospherejs.com/?q=stylus). How does this one compare, esp. with @juliancwirko's https://github.com/juliancwirko/meteor-s-jeet/issues/4 ?

PS: some of those stylus packages on Atmosphere are abandoned and should be flagged. Help with flagging would be appreciated.

**Comment by cryptoquick** [comment]
Well, this one goes to 11.

But seriously, this package is well-documented, tested, and I'd like to think I maintain it in a responsible manner. I made this because other packages lacked the functionality I needed, and I still think this is the best, most full-featured, most attractive-looking Stylus package out there. If you're happy with that explanation, I'll let you close this ticket. If not, we can discuss further, but please be sure to read the documentation, of course.

**Comment by mquandalle** [comment]
I'm the author of one of the many stylus packages for meteor https://atmospherejs.com/mquandalle/stylus
I need to take a closer look at your package @cryptoquick, but currently the main differences seems to be:

* You support autoprefixer and Axis, I don't
* I have source maps, you don't
* I support absolute include (path based on the meteor application root), you don't
* Yous support `//@import-only`, I don't

I think both packages are reasonably tested and maintained. Should we join efforts?

**Comment by cryptoquick** [comment]
I believe that would be prudent, @mquandalle, and I wouldn't mind at all helping you out on your projects. I appreciate the work you've done on your Jade plugin, and I'm aware of all the work you've done for the Meteor community. Do you have any suggestions as to how we might go about smoothly forwarding users of this package over to yours?

I can also add those missing features to yours.

**Comment by mquandalle** [comment]
Cool, it shouldn't be too difficult to converge the set of features. I also trust you so I'm happy to add you do the git repository and atmosphere (so your name will appear as one of the authors on the atmosphere website) of `mquandalle:stylus`. Does that work for you?

If yes, the next things to do would be to:
* Add autoprefixer
* Add axis
* Use your Readme documentation
* Improve the package description
* Support `//@import-only` (TBH, I didn't take a look at this feature yet, not sure what it is ;-))
* Verify that `cryptoquick:stylus-multi` tests pass on `mquandalle:stylus`

While we implement these points, you can keep your package as it is. Then when you are ready you can empty the package source and simply `api.imply("mquandalle:stylus@x.y.z")` so your users would transparently use the latest version of our stylus package. If you really want them to migrate you may also add a `console.warn("you-should-migrate-message")`, but I'm not sure it would be necessary.

**Comment by cryptoquick** [comment]
Yes, that'll all be great. I'll have to get to that in the coming week, I actually have a local Meteor meetup tonight. :)

**Comment by rhythnic** [comment]
@mquandalle @cryptoquick I think it's great that you two are coming together to make an official stylus meteor package.  What do you think about allowing the package to be configured to specify which stylus plugins to use?  Is there a way to do that?  Also, how about a protocol for allowing other packages to expose custom stylus mixins?  There's one other undocumented stylus package that does that, but it doesn't support the packages included in stylus-multi.  That package uses .mixin.styl to expose custom mixins globally.

**Comment by cryptoquick** [comment]
I've got a PR in the works, @rhythnic ... Though, I'm not sure if we're gonna want the `//@import-only` feature as well?

**Comment by rhythnic** [comment]
@cryptoquick your "//@import-only" is the same as @mquandalle 's ".import.styl", right?  Imports are usually mixins/functions/variables, which wouldn't get compiled to css anyway, unless the imports declare classes as well, in which case I could see using that feature.  Or am I missing the point, and it's more an issue of wasting cpu/memory?  If that's the case, I like the feature because it would speed up development a bit.

**Comment by cryptoquick** [comment]
Sort of... The difference is, one is in the actual file, while one is in the file system. I'm actually not 100% sure I liked the `//@import-only` statement as much as I liked @mquandalle 's approach just because I'm tacking on (relatively) undocumented syntax onto a DSL. I know they do do that for their Jade plugin, but I'm not sure if it's completely necessary here. I'm not terribly concerned about preprocessing performance in this case.

I am a little worried about breaking other people's codebases, but that's why we use semver.

**Comment by cryptoquick** [comment]
I've updated the README, so I can focus on assisting with: https://github.com/mquandalle/meteor-stylus

Closing. :smile_cat:
