### ISSUE TITLE
'nib' vendor-prefix free functionality not working

### ISSUE THREAD

**Issue by alex-wilmer** [furrio/meteor-stylus-multi#9]
In codepen.io with Stylus and nib

    *
      box-sizing border-box

yields:

    * {
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box; 
    }

In Meteor it doesn't seem like the vendor prefixed versions are being added.

**Comment by cryptoquick** [comment]
Good catch. I'll take a look at this tomorrow. :+1:

**Comment by cryptoquick** [comment]
So, I gave some thoughts to this, and I figured it out. If you use only Nib and Stylus, yes, that will happen. However, we also use Autoprefixer, which in fact removes prefixes that don't need to be there due to common browser support. I believe that is causing that behavior you're seeing. Autoprefixer, as it's configured right now, only works for the past three versions of common browsers.

See: https://github.com/postcss/autoprefixer#only-actual-prefixes

I hope that helps. Thanks for using this package, and if that doesn't meet your needs, let me know.

**Comment by alex-wilmer** [comment]
Oh great! Thanks that makes a lot of sense. This package is fantastic!

**Comment by cryptoquick** [comment]
Thanks!

**Comment by ghsamm** [comment]
what if i wanted to target more browsers, i.e change the configuration of autoprefixer?
would that be possible?
great package btw
